name: 标准系统智能体
sessions_file: sessions.json
messages_file: messages.json
skills:
  - ingest-file
  - wiki-query
layout:
  left:
    - history
    - knowledgebase
    - document
  defaultLeft: knowledgebase
  right:
    - chat
  defaultRight: chat