name: 标准个人助手
skills:
  - graph-query
  - ingest-file
  - build-knowledge-graph
layout:
  left:
    - history
    - knowledgebase
    - document
  defaultLeft: knowledgebase
  right:
    - chat
  defaultRight: chat
